"$schema" = "./node_modules/wrangler/config-schema.json"
name = "foobot"
main = "src/index.ts"
compatibility_date = "2026-01-28"
secrets_store_secrets = [
    { binding = "LINE_CHANNEL_SECRET", store_id= "9c70a29302f948cb9ff3ddbd8d2afb49", secret_name = "Foo_Channel_Secret" },
    { binding = "LINE_CHANNEL_ACCESS_TOKEN", store_id= "9c70a29302f948cb9ff3ddbd8d2afb49", secret_name = "Foo_Channel_Access_Token" }
]


[[kv_namespaces]] 
binding = "KV"
id = "f502ef723ad641c88374eb86c14129cd"

[placement]
mode = "smart"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true